
import React from 'react';
import { Project } from './types';

export const INITIAL_DATA: Project[] = [
  // Pumping Plants
  { id: 1, category: 'Pumping', utility: 'Con Edison', substation: 'Farragut/Gowanus', dateCreated: '4/16/2020', order: '154487', fatDate: 'N/A', landing: 'Dec. 2025', status: 'Critical', progress: 15, lead: 'TBD', description: 'Install 1K Gallon XLPE Tank at 6 locations. 3/4" SS pipe, valves, solenoid valve, flow meter, heat trace, PE designed foundation, Contractor to install foundation. Mostly field work; Con Ed to pour foundation (not in MAC scope anymore)', comments: 'Quote provided for bypass valve for SOV - Installation complete by 12/2025 - Need schedule / plan; Sent Con Ed submital dwgs 6/9/25 - Tanks released (job updater not working; JO is closed); Tanks on order - Automation block diagram submitted 7/18/25 - Comments sent back 8/11; Approved - Work likely to start summer 2026 - BOMs released', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 2, category: 'Pumping', utility: 'Con Edison', substation: 'Multiple Plants', dateCreated: '12/5/2022', order: 'IG836', fatDate: 'N/A', landing: 'Late March 2023', status: 'Late', progress: 95, lead: 'Jason', description: 'Liquid Level Gauge RTUs (for remote monitoring); Some locations will need new liquid levels. Multiple SO#s, JO #IG836, Engineer & Field Tech (install control panel & route wires, cable/connector terminations)', comments: '- Need to release A/D converters for Non-PLC plants (Queensbridge, no level gauge switches needed)\n- 17 total installations\n- Greenwood #3 needs level gauges (Sales to quote)\n- Woodrow level gauges & scale released (Assemble & Ship out)\n- QB2 & Narrows level gauges shipped\n- 1 installation remaining (requires level gauge installations @ Con Ed) Narrows', milestones: { design: true, mat: true, fab: true, fat: true, ship: false } },
  { id: 3, category: 'Pumping', utility: 'OUC', substation: 'Sub 25', dateCreated: '1/6/2024', order: '166453', fatDate: '09/26/24', landing: 'Dec. 2025', status: 'Critical', progress: 85, lead: 'Rich E.', description: 'Dual skid w/circulation, flow meters, limiters, normal pump RV actuator, crossover ABV valve, 120/240 single phase, 125VDC, Modicon PLC, HMI, annunciator, DNP3 serial over MM fiber, LWS, 2 Cyl SS N2 Cabinet, new foundation for N2 Cabinet, No LLG', comments: '- SO revised for MOXA media converter, SEL, Tank Sfty, and LL gauge\n- Load skid & Access. 12/12; Land 12/16\n- DSC to complete install. Dec. 2025\n- Commiss. 1/14/26? (EE & ME)', milestones: { design: true, mat: true, fab: true, fat: true, ship: false } },
  { id: 4, category: 'Pumping', utility: 'OUC', substation: 'Sub 26', dateCreated: '1/6/2024', order: '166454', fatDate: '09/26/24', landing: '02/19/25', status: 'Active', progress: 60, lead: 'Rich E.', description: 'Full PP with 3,750 gallon tank & enclosure, w/circulation, flow meters, limiters, normal pump RV actuator, crossover ABV valve, 120/240 single phase, Modicon PLC, HMI, annunciator, DNP3 serial over MM fiber, LWS, 2 LLGs, 2 Cyl SS N2 Cabinet, new foundation', comments: '- Video of PP operation w/Sub 25 12/5/24\n- Delivery 2/26 (Use new crane Co. - Simms)\n- 1Q 2026 Field FAT\n- For future PPs, J-box & Tubing Conn. to be lower so ladder not needed in field', milestones: { design: true, mat: true, fab: true, fat: false, ship: false } },
  { id: 5, category: 'Pumping', utility: 'JEA', substation: 'Northside/Southside', dateCreated: '8/7/2024', order: '168426', fatDate: 'N/A', landing: 'SS: 7/7/25 | NS: 8/4/25', status: 'Active', progress: 40, lead: 'Jason', description: 'Control Panel replacements (5) over existing dual skids:\n- 2 at Northside + N2 Manifold + 2 LL gauges + instrumentation for alarm & controls\n- 3 at Southside + N2 Manifold + 3 LL gauges + instrumentation for alarm & controls\nMAC to perform the installations\n- No portable trailer will be used at Northside', comments: '- (Do Randall PC swap field work at same time)\n- Field work to start 7/7/25; CPs on site 7/9\n- No portable trailer needed for Northside\n- Southside FAT: 7/29 (Jason): DONE\n- N.S. to start Feb/Mar 2026', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 6, category: 'Pumping', utility: 'PEPCO', substation: 'Longwood', dateCreated: '10/16/2024', order: '169187', fatDate: '12/29/2025', landing: 'Mar-26', status: 'Critical', progress: 30, lead: 'Heffron', description: '2 Ladder PP skid, PLC controls, HMI, 2 liquid level gauges, 2 tank safeties, 2 cyl tank N2 cabinet; 4 cyl tank N2 cabinet for gas pump\nUse Heffron (for welding); TMR to do field work;\n- Heffron to do welding (MAC to supply valves, flanges, SS Tubing)', comments: '- LL Gauges released; Gen BOM\n- Complete mfg 12/25; 1Q \'26 Delivery\n- Need to release N2 cabinets\n- Outlet manifold & stand released\n- Problem w/mounting panels misaligned with studs\n- Self certify factory FAT - send PEPCO scanned copy by 12/29; PEPCO to visit 2/11\n- Attach Norbeck door nameplates\n- Wrong motor J-box mounting received', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 7, category: 'Pumping', utility: 'PSE&G', substation: 'Saddlebrook A', dateCreated: '10/17/2024', order: '169198', fatDate: '3/25/2026', landing: 'Apr-26', status: 'Critical', progress: 20, lead: 'TBD', description: '24K Gal. Tank, 2 ladders, Osc., HPTD instrumentation, additional stop joint monitoring screens, 2 LLs, 2 DPT level Xmitters, IIBC required', comments: '- Full Gen. BOM released including Bard HVAC & Liquid Level Gauges (Gems)\n- Enclosure released; Delivery on 1/12/26\n- KPS will supply ceiling support beams\n- Pumps now delayed to 12/22\n- Plyco door here\n- Problem w/CP fabrication - Modify CP\n- Site visit 12/10/25 (rigging)', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 8, category: 'Pumping', utility: 'ATC', substation: 'De Pere & Red Maple', dateCreated: '1/29/2025', order: '170120', fatDate: '7/10/2025', landing: 'Mar/Apr 2026', status: 'Active', progress: 75, lead: 'TBD', description: '2-Cylinder HPGF Cabinets, Aluminum; pressure switches, gauges, transmitters, light, Ext J-box, rectifier monitoring', comments: '- All Dwgs approved (Elect. & Mech.)\n- Factory FATs complete\n- 3/30/26 Red Maple delivery (1 Wk Install.)\n- 4/6/26 De Pere delivery (1 Wk Install.)', milestones: { design: true, mat: true, fab: true, fat: true, ship: false } },
  { id: 9, category: 'Pumping', utility: 'FP&L', substation: 'Latin Quarter', dateCreated: '4/22/2025', order: '171104', fatDate: '12/19/2025', landing: 'Jan. 2026', status: 'Critical', progress: 80, lead: 'Orion', description: '15K Gallon tank, 3 stand up ladders, gas pump, moat, PLC control, hurricane enclosure & door; FP&L to supply generator & ATS, 7,500 gallons of new oil; New Leistritz pumps to be used', comments: '- Cimplicity key not ordered?\n- Load 1/5; Land 1/12/26 (Add\'l charge for weekend layover)\n- Adder for complex rigging on-site\n- Problem with Orion reed switches', milestones: { design: true, mat: true, fab: true, fat: true, ship: false } },
  { id: 10, category: 'Pumping', utility: 'PECO', substation: 'Waneeta 2', dateCreated: '5/20/2025', order: '171333', fatDate: '12/16/2025', landing: '12/22/2025', status: 'Done', progress: 100, lead: 'TBD', description: '4K Gallon tank, 4 stand up ladders, gas pump, no moat, electro-mech. controls, PLC monitoring, 6 Cyl. Nitrogen cabinet, PP to fit on existing concrete moat pit; Use IMO/Circor 3G pumps?\n- Use Bard from Inventory', comments: '- Factory FAT 12/16/25\n- Cimplicity key not ordered?\n- Load 12/18; Land 12/22\n- Need position indicator valves and custom bracket (EW to design & release); Done\n- Customer happy with plant and FAT', milestones: { design: true, mat: true, fab: true, fat: true, ship: true } },
  { id: 11, category: 'Pumping', utility: 'XCEL ENERGY', substation: 'Elliot Park PP', dateCreated: '5/21/2025', order: '171338', fatDate: '4/8/2026', landing: '4/15/2026', status: 'Critical', progress: 45, lead: 'TBD', description: '2 ladder dual skid, PLC control, gas pump, 3 outlet manifold, tank sfty assy, tank N2 supply system, 2 Orion LL gauges; Very similar to 5th St. skid; 2 portable cubes needed for install.', comments: '- Mechanical & Electrical dwgs approved\n- Elect. Submittal sent; Now 1 phase power\n- Released Gen. BOM 9/24/25\n- 3G pump approved; Expected 11/21\n- Skid piping final assy released\n- CP Final Assy released', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 12, category: 'Pumping', utility: 'XCEL ENERGY', substation: 'Elliot Park HX', dateCreated: '6/6/2025', order: '171492', fatDate: '5/13/2026', landing: '10/7/2026', status: 'Active', progress: 10, lead: 'TBD', description: 'HX plant; 1MBtu/hr, (2) 150 GPM pumps, (2) 10 GPM pumps, PLC Controls, VFDs; - No IIBC required per customer', comments: '- Mech dwgs submitted; Comments received; Mechanical resubmittal sent 8/26\n- Elect. Dwgs submitted; Comments received\n- Steel beams pre-released for sand blasting\n- Pumps/motors released (Leistritz)\n- Release other long lead time components\n- Customer wants 2nd personnel door (adder)', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 13, category: 'Pumping', utility: 'XCEL ENERGY', substation: 'Soncy PP', dateCreated: '7/1/2025', order: '171715', fatDate: '9/16/2026', landing: 'Sept. 2026', status: 'Active', progress: 15, lead: 'TBD', description: '1 full PP w/4K gallon tank w/1 partition, static (no circ.), moat walls, 210H pumps, flow limiters, gas pump, 3 phase 120/208, AC Disc. Sw. w/Manual throwover for generator, GE RX3i PLC control, HMI, annunciator, DNP3 serial over MM fiber, LWS, 2 LLGs, 2 Cyl SS N2 Cabinet & 6 Cyl SS N2 Cab.; Fire Vapor Sfty RV; Jacking lugs needed', comments: '- Mech. submittal Dwgs sent 8/27/25\n- Need Elect. submittal dwgs\n- Release long lead time material\n- Received comments from Powers; Elect. & Mechanical dwgs approved', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 14, category: 'Pumping', utility: 'XCEL ENERGY', substation: 'Lawrence Park PP', dateCreated: '7/9/2025', order: '171740', fatDate: '9/17/2026', landing: '3/1/2027', status: 'Active', progress: 5, lead: 'TBD', description: '1 full PP w/4K gallon tank w/1 partition, static (no circulation), moat walls, 210H pumps, flow limiters, gas pump, 3 phase 120/208, AC Disc. Sw. w/Manual throwover for generator, GE RX3i PLC control, HMI, annunciator, DNP3 serial over MM fiber, LWS, 2 LLGs, 2 Cyl SS N2 Cabinet & 6 Cyl SS N2 Cab.; Fire Vapor Sfty RV; Portable Trailer needed 12/4/26; Jacking lugs needed', comments: '- Mech submittal Dwgs sent 8/27/25\n- Need Elect. submittal dwgs\n- Release long lead time material\n- Received comments from Powers; Mechanical dwgs approved)\n- Submit Elect. Dwgs Jan. 2026', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },
  { id: 15, category: 'Pumping', utility: 'Xcel Energy', substation: 'Guthrie', dateCreated: '7/14/2025', order: '171759', fatDate: '10/21/2025', landing: '11/14/2025', status: 'Critical', progress: 50, lead: 'TBD', description: 'Communication Cabinet w/ external disc. Switch, SEL I/O module, fiber panel, relays, DC PS, heater\nXO Cabinet w/ I/O module, fiber panel, relays, DC PS, Selector Sw/Lts, heater, valve actuator', comments: '- Submittal Dwgs sent 8/18/25: All approved\n- Higher priority over Soncy & Lawrence Park\n- XO Cabinet design can be released later\n- Add insulation to XO Cabinet\n- Enclosure door cutout for Comm Cab. released\n- MAC to mount and wire pressure switches', milestones: { design: true, mat: true, fab: true, fat: true, ship: false } },
  { id: 16, category: 'Pumping', utility: 'Com Ed', substation: 'Taylor, Garfield', dateCreated: '12/8/2025', order: '173021', fatDate: 'Various', landing: 'Apr/May 2027', status: 'Critical', progress: 0, lead: 'TBD', description: '4 ACOP (Heat Exchanger) plants\n- Taylor & Garfield: April 2027 Commiss\n- 26th & Federal (1&2): May 2027 Commiss', comments: '- Submit IMO pumps / motors for approval\n- Customer to decide if Control house & cooler are split (separate base skids)', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },

  // Field Service
  { id: 17, category: 'Field Service', utility: 'Con Edison', substation: 'Various PP', dateCreated: '3/18/2024', order: 'Various', fatDate: 'N/A', landing: 'TBD', status: 'Critical', progress: 10, lead: 'Field Tech', description: 'RX3i Upgrade.\nMurray Hill (167173), WTC (167174), W 19th St. (167175), Astoria X (167214), Astoria Y (167221), 49th St. PH2 (167422), 49th St. PH1 (167425), 19th St. PH2 (167426), Ave A PH1 (167427), E. 29th St PH1 (167428), E. 29th St. PH2 (167429), Ave A PH2 (167430), Cherry St. (168243), W. 40th St. (168242)', comments: '- Material Only\n- May/June 2025\n- Need order for installation', milestones: { design: false, mat: true, fab: false, fat: false, ship: false } },
  { id: 18, category: 'Field Service', utility: 'Con Edison', substation: 'Corona', dateCreated: '3/21/2025', order: '170773', fatDate: 'N/A', landing: '03/21/25', status: 'Critical', progress: 0, lead: 'Field Tech', description: 'Replace vibration transducer', comments: '- Scheduled for 9/29', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },
  { id: 19, category: 'Field Service', utility: 'Com Ed', substation: 'Taylor', dateCreated: '8/5/2025', order: '171911', fatDate: 'N/A', landing: 'Dec. 2025', status: 'Active', progress: 20, lead: 'Field Tech', description: 'Replace 3 N2 manifolds mounted to wall, replace copper tubing with SS', comments: '- BOM released (working on dwg)', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 20, category: 'Field Service', utility: 'Com Ed', substation: 'Natoma 6', dateCreated: '', order: '-', fatDate: 'N/A', landing: '12/29/25', status: 'Active', progress: 0, lead: 'Field Tech', description: 'Liquid Level Xmitters (Calibration)', comments: '- Need to respond to customer', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },
  { id: 21, category: 'Field Service', utility: 'Southwire', substation: 'Magella X', dateCreated: '9/8/2025', order: '172463', fatDate: 'N/A', landing: '9/18/125', status: 'Active', progress: 100, lead: 'Field Tech', description: 'Installation supervision for RV, regulator, & sealing bushings for MAC HPGF cabinet', comments: 'Field Service Expected Completion 9/18', milestones: { design: false, mat: false, fab: false, fat: false, ship: true } },
  { id: 22, category: 'Field Service', utility: 'Eversource', substation: 'Glenbrook', dateCreated: '10/24/2025', order: '172773', fatDate: 'N/A', landing: '2/27/2026', status: 'Critical', progress: 90, lead: 'Field Tech', description: 'Repair termination tubing (tighten and/or replace fittings), test for leaks; Replace 6 PSs in term. cabinet, replace 6 insulated cplgs', comments: 'All material released including arc suppressor', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 23, category: 'Field Service', utility: 'First Energy', substation: 'Hamilton & Lakeshore', dateCreated: '10/31/2025', order: '172816', fatDate: 'N/A', landing: '1/27/2026', status: 'Active', progress: 0, lead: 'Field Tech', description: 'HMI troubleshooting & updates; Semi-annual maintenance & PP training, software training', comments: 'Upcoming', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },
  { id: 24, category: 'Field Service', utility: 'Con Edison', substation: 'Dunwoodie', dateCreated: '12/9/2025', order: '173406', fatDate: 'N/A', landing: '1/30/2026', status: 'Done', progress: 100, lead: 'Field Tech', description: 'Troubleshoot PP1 UPS & HMI\nTroubleshoot PP2 lost set points on loss of power', comments: 'Done', milestones: { design: false, mat: false, fab: false, fat: false, ship: true } },
  { id: 25, category: 'Field Service', utility: 'Con Edison', substation: 'Fresh Kills', dateCreated: '12/9/2025', order: '173402', fatDate: 'N/A', landing: '1/30/2026', status: 'Active', progress: 0, lead: 'Field Tech', description: 'Troubleshoot PP1 oil migration', comments: '', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },
  { id: 26, category: 'Field Service', utility: 'ONCOR', substation: 'TOPEKA', dateCreated: '12/29/2025', order: '173444', fatDate: '16-Feb', landing: '2/19/2026', status: 'Critical', progress: 0, lead: '1 EE & 1 Shop', description: 'Annual Maintenance, replace HMI, replace control board in ASCO XFR switch, replace chart recorder', comments: '1 EE & 1 Shop guy needed for field', milestones: { design: false, mat: false, fab: false, fat: false, ship: false } },

  // EHV
  { id: 27, category: 'EHV', utility: 'Taihan', substation: 'Manhole Racking', dateCreated: '4/11/2024', order: '167295', fatDate: 'N/A', landing: 'TBD', status: 'Critical', progress: 25, lead: 'TBD', description: 'Replacement Hangers, MAV', comments: 'Project is delayed. Repeat order; Released 8/11/25', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 28, category: 'EHV', utility: 'Con Edison', substation: 'Casing Parts', dateCreated: '', order: '171892', fatDate: '', landing: '1/29/2026', status: 'Active', progress: 80, lead: 'TBD', description: 'Casing Parts 574-2234', comments: 'Repeat order; Released 8/11/25', milestones: { design: true, mat: true, fab: true, fat: false, ship: false } },
  { id: 29, category: 'EHV', utility: 'Taihan', substation: 'O&R Racks', dateCreated: '', order: '171905', fatDate: '', landing: '20-Nov', status: 'Active', progress: 20, lead: 'TBD', description: '22 Splice, 3 Pull, 304SS', comments: '', milestones: { design: true, mat: true, fab: false, fat: false, ship: false } },
  { id: 30, category: 'EHV', utility: 'Con Edison', substation: 'Splice Kit', dateCreated: '8/25/2025', order: '172374', fatDate: '', landing: '12/15/2025', status: 'Done', progress: 100, lead: 'TBD', description: 'Splice Kit 138KV including FM connectors, spiders, LPP Tapes, braids, taper templates; End Plate', comments: 'Released end plate, casing, splice kit', milestones: { design: true, mat: true, fab: true, fat: true, ship: true } },
  { id: 31, category: 'EHV', utility: 'Con Edison', substation: 'Pressure Test Assy', dateCreated: '8/25/2025', order: '172375', fatDate: '', landing: '2/9/2026', status: 'Active', progress: 20, lead: 'TBD', description: 'Pressure Test Assy w/filter bypass, SS pipe stubs, base plate & mounting plate (no diffusion chamber)', comments: '', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 32, category: 'EHV', utility: 'Con Edison', substation: 'Wye Joint', dateCreated: '8/25/2025', order: '172376', fatDate: '', landing: '3/9/2026', status: 'Active', progress: 20, lead: 'TBD', description: 'Wye Joint, splice kit, includes connectors, crepe paper tapes, braids, taper templates', comments: '', milestones: { design: true, mat: false, fab: false, fat: false, ship: false } },
  { id: 33, category: 'EHV', utility: 'Taihan', substation: 'Racking ONCOR', dateCreated: '', order: '172459', fatDate: '', landing: '12/23/2025', status: 'Active', progress: 50, lead: 'TBD', description: '4 Splice, 4 Terms, 304SS', comments: '', milestones: { design: true, mat: true, fab: true, fat: false, ship: false } },
  { id: 34, category: 'EHV', utility: 'Taihan', substation: 'Racking XCEL', dateCreated: '', order: '172683', fatDate: '', landing: '2/16/2026', status: 'Active', progress: 50, lead: 'TBD', description: '24 Splice, 2 Pull, 316SS', comments: '', milestones: { design: true, mat: true, fab: true, fat: false, ship: false } },
  { id: 35, category: 'EHV', utility: 'Con Edison', substation: 'Casing Parts', dateCreated: '10/29/2025', order: '172797', fatDate: '', landing: '1/14/2026', status: 'Active', progress: 40, lead: 'TBD', description: 'Casing Parts 574-2234', comments: '', milestones: { design: true, mat: true, fab: true, fat: false, ship: false } },
];

export const Icon = ({ path, className }: { path: React.ReactNode; className?: string }) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    {path}
  </svg>
);

export const DashboardIcon = (props: any) => <Icon {...props} path={<><rect x="3" y="3" width="7" height="9"></rect><rect x="14" y="3" width="7" height="5"></rect><rect x="14" y="12" width="7" height="9"></rect><rect x="3" y="16" width="7" height="5"></rect></>} />;
export const ListIcon = (props: any) => <Icon {...props} path={<><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></>} />;
export const CalendarIcon = (props: any) => <Icon {...props} path={<><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></>} />;
export const SearchIcon = (props: any) => <Icon {...props} path={<><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></>} />;
export const EditIcon = (props: any) => <Icon {...props} path={<><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></>} />;
export const SaveIcon = (props: any) => <Icon {...props} path={<><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></>} />;
export const LogIcon = (props: any) => <Icon {...props} path={<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></>} />;
export const FilterIcon = (props: any) => <Icon {...props} path={<><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></>} />;
export const CheckIcon = (props: any) => <Icon {...props} path={<polyline points="20 6 9 17 4 12"></polyline>} />;
export const ChevronDownIcon = (props: any) => <Icon {...props} path={<polyline points="6 9 12 15 18 9"></polyline>} />;
export const AlertIcon = (props: any) => <Icon {...props} path={<><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></>} />;
export const TruckIcon = (props: any) => <Icon {...props} path={<><rect x="1" y="3" width="15" height="13"></rect><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon><circle cx="5.5" cy="18.5" r="2.5"></circle><circle cx="18.5" cy="18.5" r="2.5"></circle></>} />;
export const ToolIcon = (props: any) => <Icon {...props} path={<><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path></>} />;
export const ZapIcon = (props: any) => <Icon {...props} path={<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>} />;
export const LogoutIcon = (props: any) => <Icon {...props} path={<><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></>} />;
export const PlusIcon = (props: any) => <Icon {...props} path={<><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></>} />;
export const ClipboardIcon = (props: any) => <Icon {...props} path={<><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect><line x1="9" y1="12" x2="15" y2="12"></line><line x1="9" y1="16" x2="15" y2="16"></line></>} />;
